In [1]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])


print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [ ]:
percentage=100*A/cal.reshape(1,4) #divided 1,4 matrix
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### python numpy vectors


In [7]:
import numpy as np

a=np.random.randn(5)

In [8]:
print(a)

[ 1.26761214  0.45223928 -0.64126264 -0.38312258  0.19015664]


In [9]:
print(a.shape)

(5,)


In [11]:
print(a.T) #transpose

[ 1.26761214  0.45223928 -0.64126264 -0.38312258  0.19015664]


In [13]:
print(np.dot(a,a.T))

2.4055211202691296


In [14]:
a=np.random.randn(5,1)
print(a)

[[-0.43289289]
 [-1.54014768]
 [ 0.10577746]
 [ 0.23595723]
 [ 0.16932724]]


In [15]:
print(a.T)

[[-0.43289289 -1.54014768  0.10577746  0.23595723  0.16932724]]


In [16]:
print(np.dot(a,a.T))

[[ 0.18739625  0.66671898 -0.04579031 -0.10214421 -0.07330056]
 [ 0.66671898  2.37205489 -0.16291291 -0.36340898 -0.26078896]
 [-0.04579031 -0.16291291  0.01118887  0.02495896  0.01791101]
 [-0.10214421 -0.36340898  0.02495896  0.05567581  0.03995399]
 [-0.07330056 -0.26078896  0.01791101  0.03995399  0.02867171]]
