In [251]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [252]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [253]:
df.shape

(569, 33)

In [254]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [255]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [256]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [257]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [258]:
X_train

array([[-0.13120129, -1.3707285 , -0.16373878, ..., -0.50089876,
        -0.83104371,  0.16545531],
       [-1.00621735,  0.01267264, -0.9848173 , ..., -1.22354934,
        -0.10992811, -0.46931809],
       [-1.20364978, -0.50638488, -1.18176383, ..., -0.90622637,
        -0.58366549,  0.02935467],
       ...,
       [-1.1762363 , -0.44319527, -1.16491708, ..., -0.86840374,
         0.15361862, -0.56295533],
       [ 0.02663389,  1.94446934,  0.02358104, ..., -0.47662676,
        -1.62330075, -0.33648386],
       [-0.49394529, -0.96676634, -0.54840624, ..., -0.98678561,
        -0.9636255 , -1.32838534]])

In [259]:
y_train

220    B
104    B
110    B
564    M
374    B
      ..
107    B
510    B
206    B
238    B
404    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [260]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [261]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,

### Numpy arrays to PyTorch tensors

In [262]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [263]:
X_train_tensor.shape

torch.Size([455, 30])

In [264]:
X_test_tensor.shape

torch.Size([114, 30])

In [265]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [266]:
X_train_tensor = X_train_tensor.float()
X_test_tensor  = X_test_tensor.float()
y_train_tensor = y_train_tensor.float()
y_test_tensor  = y_test_tensor.float()




In [267]:
import torch.nn as nn

In [268]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()



  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out







### Important Parameters

In [269]:
learning_rate = 0.1
epochs = 25

In [270]:
loss_fn=nn.BCELoss()

In [271]:
type(loss_fn)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [272]:
print(X_train_tensor.dtype)
print(y_pred.dtype)
print(X_test_tensor.dtype)
print(model.linear.weight.dtype)


torch.float32
torch.float32
torch.float32
torch.float32


In [273]:
X_train_tensor.shape

torch.Size([455, 30])

In [274]:
X_test_tensor.shape


torch.Size([114, 30])

In [275]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
#model.parameter retreives an iterator over all the trainable parameters



# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_fn(y_pred, y_train_tensor.view(-1,1))  #resahping using view


  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update (optimizer)
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6293718218803406
Epoch: 2, Loss: 0.4839846193790436
Epoch: 3, Loss: 0.4069228768348694
Epoch: 4, Loss: 0.3587362468242645
Epoch: 5, Loss: 0.32524392008781433
Epoch: 6, Loss: 0.30032315850257874
Epoch: 7, Loss: 0.2808762788772583
Epoch: 8, Loss: 0.26515865325927734
Epoch: 9, Loss: 0.25210896134376526
Epoch: 10, Loss: 0.24104280769824982
Epoch: 11, Loss: 0.23149770498275757
Epoch: 12, Loss: 0.22314926981925964
Epoch: 13, Loss: 0.21576258540153503
Epoch: 14, Loss: 0.20916298031806946
Epoch: 15, Loss: 0.20321765542030334
Epoch: 16, Loss: 0.19782349467277527
Epoch: 17, Loss: 0.19289915263652802
Epoch: 18, Loss: 0.18837934732437134
Epoch: 19, Loss: 0.1842111051082611
Epoch: 20, Loss: 0.18035081028938293
Epoch: 21, Loss: 0.1767621785402298
Epoch: 22, Loss: 0.17341472208499908
Epoch: 23, Loss: 0.17028267681598663
Epoch: 24, Loss: 0.16734395921230316
Epoch: 25, Loss: 0.1645795702934265


In [276]:
model.linear.bias

Parameter containing:
tensor([-0.2266], requires_grad=True)

### Evaluation

In [277]:
X_test_tensor.shape


torch.Size([114, 30])

In [278]:
X_train_tensor.shape

torch.Size([455, 30])

In [279]:
y_test_tensor.shape

torch.Size([114])

In [280]:
y_train_tensor.shape

torch.Size([455])

In [281]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5609418153762817
