In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.80530397,  0.14696805, -0.84162137, ..., -1.3101648 ,
        -0.52786065, -0.42977291],
       [-0.83339437,  0.51547747, -0.85589458, ..., -1.08636567,
         0.15849392, -0.69772598],
       [ 0.30707551,  2.66356083,  0.46743498, ...,  1.8369915 ,
         1.98167443,  3.11212909],
       ...,
       [-0.79406782, -0.23553539, -0.73436847, ...,  0.10915289,
         0.70233573,  2.49966495],
       [ 1.69474083,  0.10731831,  1.59705682, ...,  0.42344339,
         0.28790206, -1.34846913],
       [ 1.49529905,  0.03035115,  1.40946619, ...,  1.29495425,
         0.81863924,  0.30135615]])

In [9]:
y_train

522    B
419    B
562    M
373    M
38     M
      ..
336    B
365    M
242    B
321    M
254    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,

### Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
X_test_tensor.shape

torch.Size([114, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

In [17]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset): #inheriting from dataset class

  def __init__(self, features, labels):
      self.features= features
      self.labels=labels

  def __len__(self):

     return self.features.shape[0]

  def __getitem__(self,idx):
     # can apply transformation too

     return self.features[idx], self.labels[idx]

In [18]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [19]:
train_dataset[10]

(tensor([ 1.8155,  0.4758,  1.8703,  1.8583,  0.8945,  1.1541,  1.6190,  1.6378,
          0.1784, -0.0742,  0.6509,  0.0313,  0.6412,  0.7203, -0.0802,  0.1678,
          0.2867,  0.4945, -1.1279, -0.0046,  1.5471,  0.8462,  1.6462,  1.5094,
          0.6286,  0.6667,  1.1534,  1.4680, -0.6540,  0.3282]),
 tensor(1.))

In [21]:
train_loader=DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader=DataLoader(test_dataset, batch_size=32, shuffle=True)

In [22]:
import torch.nn as nn

In [23]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()



  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out







### Important Parameters

In [24]:
learning_rate = 0.1
epochs = 25

In [26]:
loss_fn=nn.BCELoss()

In [31]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
#model.parameter retreives an iterator over all the trainable parameters


In [34]:
#training pipeline


# define loop
for epoch in range(epochs):

  for  batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_fn(y_pred, batch_labels.view(-1,1))  #resahping using view


    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update (optimizer)
    optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.36621230840682983
Epoch: 2, Loss: 0.4899838864803314
Epoch: 3, Loss: 0.11220906674861908
Epoch: 4, Loss: 0.07695431262254715
Epoch: 5, Loss: 0.11730896681547165
Epoch: 6, Loss: 0.21397753059864044
Epoch: 7, Loss: 0.03292366489768028
Epoch: 8, Loss: 0.07802339643239975
Epoch: 9, Loss: 0.07011623680591583
Epoch: 10, Loss: 0.3113730549812317
Epoch: 11, Loss: 0.15457512438297272
Epoch: 12, Loss: 0.01499325130134821
Epoch: 13, Loss: 0.0038978694938123226
Epoch: 14, Loss: 0.07309369742870331
Epoch: 15, Loss: 0.010164270177483559
Epoch: 16, Loss: 0.06712566316127777
Epoch: 17, Loss: 0.09047435969114304
Epoch: 18, Loss: 0.030104393139481544
Epoch: 19, Loss: 0.09123896062374115
Epoch: 20, Loss: 0.6701842546463013
Epoch: 21, Loss: 0.08308589458465576
Epoch: 22, Loss: 0.007183441426604986
Epoch: 23, Loss: 0.017598502337932587
Epoch: 24, Loss: 0.01617584563791752
Epoch: 25, Loss: 0.007820509374141693


In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.2266], requires_grad=True)

### Evaluation

In [ ]:
X_test_tensor.shape


torch.Size([114, 30])

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_test_tensor.shape

torch.Size([114])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [38]:
# model evaluation
model.eval()
accuracy_list=[]

with torch.no_grad():
  for batch_features, batch_labels in test_loader:

    y_pred=model(batch_features) #forward pass
    y_pred=(y_pred> 0.8).float() #convetting prob into binary

    #accurary for current batch

    batch_accuracy=(y_pred.view(-1,1) == batch_labels.view(-1,1)).float().mean()
    accuracy_list.append(batch_accuracy)


  overall_acc=sum(accuracy_list)/len(accuracy_list)
  print(f'Accuracy: {overall_acc:.4F}')


Accuracy: 0.9410
