## code flow

- load the dataset
- basic preprocessing
- training process
    - create a model
    - forward pass
    - loss calculation
    - backprop
    - parameters update

- model evaluation


In [2]:
!pip install -U scikit-learn


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 27.4 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1


In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
#train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [8]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_train

array([[-3.15028151e-01, -1.44552859e-03, -3.93161822e-01, ...,
        -1.56273193e+00, -7.53138423e-01, -1.14186462e+00],
       [ 2.44903663e-01,  1.16897746e-01,  3.19554721e-01, ...,
         1.43171318e+00, -1.13009586e-01, -1.12117601e-01],
       [ 7.49741076e-02,  2.05655203e-01,  8.54742732e-02, ...,
         1.01778968e+00,  2.99688216e+00,  8.91687206e-01],
       ...,
       [ 2.48184519e+00,  1.16897746e-01,  2.40653702e+00, ...,
         1.65436517e+00,  6.91328459e-03, -6.18784901e-01],
       [-2.34241969e-01, -7.86607642e-01, -2.36839596e-01, ...,
         8.23529557e-01,  1.01005189e+00,  9.07570193e-01],
       [-5.12815010e-01,  1.71680779e+00, -4.51984103e-01, ...,
         4.51446703e-01,  5.04431140e-01,  1.90819840e+00]])

In [10]:
y_train

58     B
94     M
199    M
454    B
497    B
      ..
10     M
544    B
503    M
81     B
193    M
Name: diagnosis, Length: 455, dtype: object

In [11]:
#label encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_test

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1])

In [13]:
#numpy array to pytorch tensors

X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)


In [14]:
X_train_tensor.shape   #30 weights

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [33]:
#defining the model

class simpleNN():

  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True) #features(weight of 30,1 matrix)
    self.bias=torch.zeros(1,dtype=torch.float64, requires_grad=True)


  def forward(self,X):  #forward pass
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred


  def loss_fn(self,y_pred,y):
    epsilon=1e-8
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss




In [34]:
learning_rate=0.1
epochs=25

In [35]:
#creatng the model
model=simpleNN(X_train_tensor)
model.weights


#define loop
for epoch in range(epochs):

  #forward pass
  y_pred=model.forward(X_train_tensor)

  #losss calculate

  loss=model.loss_fn(y_pred,y_train_tensor)
  print(f"epoch:{epoch+1},loss:{loss.item()}")

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():   #stopping graditn tracking
    model.weights-=learning_rate*model.weights.grad
    model.bias-= learning_rate* model.bias.grad

  # zero gradiets
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  #print loss in each epoch
  print(  f"epoch:{epoch+1},loss:{loss.item()}")


epoch:1,loss:3.380362904829083
epoch:1,loss:3.380362904829083
epoch:2,loss:3.232989721634608
epoch:2,loss:3.232989721634608
epoch:3,loss:3.0802555363218205
epoch:3,loss:3.0802555363218205
epoch:4,loss:2.9256720832319454
epoch:4,loss:2.9256720832319454
epoch:5,loss:2.768773399880104
epoch:5,loss:2.768773399880104
epoch:6,loss:2.607442769798847
epoch:6,loss:2.607442769798847
epoch:7,loss:2.4472245785917117
epoch:7,loss:2.4472245785917117
epoch:8,loss:2.285957668705317
epoch:8,loss:2.285957668705317
epoch:9,loss:2.1284552024380887
epoch:9,loss:2.1284552024380887
epoch:10,loss:1.9746421970454011
epoch:10,loss:1.9746421970454011
epoch:11,loss:1.8195224119072384
epoch:11,loss:1.8195224119072384
epoch:12,loss:1.6710985455647362
epoch:12,loss:1.6710985455647362
epoch:13,loss:1.5354225703836233
epoch:13,loss:1.5354225703836233
epoch:14,loss:1.4140638945076927
epoch:14,loss:1.4140638945076927
epoch:15,loss:1.3079403679939603
epoch:15,loss:1.3079403679939603
epoch:16,loss:1.2168892234826119
epoch

In [36]:
model.weights

tensor([[ 0.5251],
        [ 0.3961],
        [-0.1007],
        [-0.2349],
        [-0.1006],
        [ 0.2359],
        [-0.2115],
        [-0.0587],
        [-0.3940],
        [ 0.4257],
        [-0.1715],
        [ 0.3300],
        [ 0.0966],
        [-0.2263],
        [ 0.3311],
        [ 0.1931],
        [ 0.2929],
        [-0.0431],
        [ 0.2074],
        [-0.0552],
        [ 0.3162],
        [ 0.0241],
        [-0.1994],
        [-0.0878],
        [ 0.1184],
        [ 0.3463],
        [-0.0228],
        [-0.4541],
        [ 0.5557],
        [-0.4172]], dtype=torch.float64, requires_grad=True)

In [38]:
model.bias

tensor([-0.1814], dtype=torch.float64, requires_grad=True)

In [45]:
#evaluation

with torch.no_grad():  #stopping gradient stop
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()

  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy:{accuracy.item()}")





accuracy:0.5203139185905457
