In [1]:
import torch
import torch.nn as nn #handling the autograd functionaility internally

class Model(nn.Module):   #inherit from nn module , otherwise it wont be able to access nnn module'sm offering


    def __init__(self, num_features):
        #single neuron
       super().__init__()  #invoking parent class constructor using super
       self.linear=nn.Linear(num_features,1)  #(input,output)  ,layer=linear
       self.sigmoid=nn.Sigmoid()


    #forward pass
    def forward(self, features):

      out=self.linear(features)  #wx+b
      out=self.sigmoid(out)

      return out




In [3]:
#creating dataset

features= torch.rand(10,5)  #10 rows, 5 columsn( 5 features)

#creating model
model=Model(features.shape[1])  #dimension =1 (rows)

#calling mdel
model(features)   #can me model.foward(features)  , calling as a fucntion

tensor([[0.6571],
        [0.6729],
        [0.6895],
        [0.7315],
        [0.7311],
        [0.6525],
        [0.6026],
        [0.5792],
        [0.6606],
        [0.6662]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.4306,  0.3059,  0.4097, -0.3139, -0.0098]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([0.2072], requires_grad=True)

In [7]:
!pip install torchinfo

In [8]:
#to visualize
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
#6 [params] as 5 weights and 1 bias

In [12]:
#now with hidden layer
class Model1(nn.Module):   #inherit from nn module , otherwise it wont be able to access nnn module'sm offering


    def __init__(self, num_features):

       super().__init__()  #invoking parent class constructor using super
       self.linear1=nn.Linear(num_features,3)  #getting 5 input , and output getting 3 weights
       self.relu=nn.ReLU()
       self.linear2=nn.Linear(3,1)
       self.sigmoid=nn.Sigmoid()

    #forward pass
    def forward(self, features):

      out=self.linear1(features)  #wx+b
      out=self.relu(out)
      out=self.linear2(out)
      out=self.sigmoid(out)

      return out


In [15]:
#creating dataset

features= torch.rand(10,5)  #10 rows, 5 columsn( 5 features)

#creating model
model=Model(features.shape[1])  #dimension =1 (rows)

#calling mdel
model(features)   #can me model.foward(features)  , calling as a fucntion

tensor([[0.3790],
        [0.3613],
        [0.3773],
        [0.3619],
        [0.3695],
        [0.3756],
        [0.3836],
        [0.3676],
        [0.3573],
        [0.3599]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear2.weight

Parameter containing:
tensor([[-0.2059,  0.1214, -0.0832]], requires_grad=True)

In [17]:
model.linear1.weight

Parameter containing:
tensor([[-0.3952,  0.3936,  0.0122,  0.1936, -0.1752],
        [ 0.4005, -0.1427,  0.3199,  0.2725,  0.3555],
        [ 0.2854, -0.3948, -0.2081,  0.3191, -0.2204]], requires_grad=True)

In [19]:
#now with hidden layer ( to minimize this using sequnetila containers)
class Model1(nn.Module):   #inherit from nn module , otherwise it wont be able to access nnn module'sm offering


    def __init__(self, num_features):

       super().__init__()  #invoking parent class constructor using super
       self.network=nn.Sequential(
           nn.Linear(num_features,3),
           nn.ReLU(),
           nn.Linear(3,1),
           nn.Sigmoid(),
         )

    #forward pass
    def forward(self, features):

      out=self.network(features)

      return out


In [20]:
#creating dataset

features= torch.rand(10,5)  #10 rows, 5 columsn( 5 features)

#creating model
model=Model(features.shape[1])  #dimension =1 (rows)

#calling mdel
model(features)   #can me model.foward(features)  , calling as a fucntion

tensor([[0.6098],
        [0.6231],
        [0.5807],
        [0.5890],
        [0.5607],
        [0.6224],
        [0.6131],
        [0.6047],
        [0.6114],
        [0.6186]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear1.weight

Parameter containing:
tensor([[-0.4240,  0.0621,  0.0228, -0.4188,  0.4377],
        [ 0.3069,  0.4227, -0.3327, -0.3678, -0.3225],
        [-0.2218,  0.2168,  0.3672, -0.0152, -0.3447]], requires_grad=True)