In [2]:
import torch
print(torch.__version__)

2.9.0+cu128


In [3]:
if torch.cuda.is_available():
  print("gpu is available")
  print(f"using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("Gpu is not available, using cpu")

gpu is available
using gpu:Tesla T4


In [4]:
## creating a tensor

#using empty (allocate memory and show the values present at it)
a=torch.empty(1,3)

In [5]:
type(a)

torch.Tensor

In [6]:
# suing zeroes
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(1,2)

tensor([[1., 1.]])

In [8]:
torch.rand(1,3)

tensor([[0.9106, 0.3957, 0.9931]])

In [9]:
#use of seed ( to get the same rand value mentioning the value of seed)
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[4,3,7],[5,7,1]])

tensor([[4, 3, 7],
        [5, 7, 1]])

In [11]:
print("using arange", torch.arange(0,10,2))

using arange tensor([0, 2, 4, 6, 8])


In [12]:
print("using linspace",torch.linspace(0,10,10)) #linearly spaced (evenly spaced)

using linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [13]:
print("using eye",torch.eye(5))

using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [14]:
print('using full', torch.full((3,3),6))

using full tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])


In [15]:
## tensors shapes
x=torch.tensor([[1,2,3],[4,5,6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
#making tensor or same size
torch.empty_like(x)

tensor([[    135326793219472,           650027888,                   0],
        [                  0,                   0, 8319683848551211643]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x,dtype=torch.float32)  #failed as rand genrate float like

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [21]:
x.dtype

torch.int64

In [22]:
#assign data type

In [23]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
#datatype in pytorch


| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [27]:
x=torch.rand(2,2)

In [28]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [29]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [30]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [31]:
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [32]:
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [33]:
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [34]:
#element wise operation
a=torch.rand(2,3)
b=torch.rand(2,3)

In [35]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [36]:
a-b


tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [37]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [38]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [39]:
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [40]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [41]:
 c=torch.tensor([1,2,-5,3])

In [42]:
torch.abs(c)

tensor([1, 2, 5, 3])

In [43]:
torch.neg(c)

tensor([-1, -2,  5, -3])

In [44]:
d=torch.tensor([1.4,2.5,3.5,4.5])
torch.round(d)

tensor([1., 2., 4., 4.])

In [45]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [46]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.5000, 3.0000, 3.0000])

### 3. Reduction operation

1.   List item
2.   List item



In [48]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [49]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [50]:
torch.sum(e)

tensor(24.)

In [51]:
torch.sum(e,dim=0) #sum of cols

tensor([ 8.,  0., 16.])

In [52]:
torch.sum(e,dim=1)  #sum of row

tensor([15.,  9.])

In [53]:
torch.mean(e)

tensor(4.)

In [54]:
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [55]:
torch.median(e)

tensor(0.)

In [56]:
torch.max(e)
torch.min(e)

tensor(0.)

In [57]:
#product
torch.prod(e)


tensor(0.)

In [58]:
#standard deviation
torch.std(e)


tensor(4.4272)

In [59]:
#variance
torch.var(e)

tensor(19.6000)

In [60]:
#argmax (position of max element)
torch.argmax(e)

tensor(5)

In [61]:
#argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [62]:
f=torch.randint(size=(2,3), low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)


tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [63]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [64]:
#dot product
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])
torch.dot(vec1,vec2)

tensor(11)

In [65]:
#transpose
torch.transpose(f,0,1)


tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [66]:
h=torch.randint(size=(2,2),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9.],
        [8., 9.]])

In [67]:
torch.det(h)
#determinant

tensor(-27.0000)

In [68]:
#inverse
torch.inverse(h)

tensor([[-0.3333,  0.3333],
        [ 0.2963, -0.1852]])

### 5. Comparison operations

In [69]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3, 6],
        [1, 5, 5]])


In [70]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [71]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 3.],
        [8., 8., 3.]])

In [72]:
torch.log(k)

tensor([[  -inf, 1.3863, 1.0986],
        [2.0794, 2.0794, 1.0986]])

In [73]:
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 2.0086e+01],
        [2.9810e+03, 2.9810e+03, 2.0086e+01]])

In [74]:
torch.sqrt(k)


tensor([[0.0000, 2.0000, 1.7321],
        [2.8284, 2.8284, 1.7321]])

In [75]:
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.9526],
        [0.9997, 0.9997, 0.9526]])

In [76]:
torch.softmax(k,dim=0)

tensor([[3.3535e-04, 1.7986e-02, 5.0000e-01],
        [9.9966e-01, 9.8201e-01, 5.0000e-01]])

In [77]:
torch.relu(k)

tensor([[0., 4., 3.],
        [8., 8., 3.]])

## Inplace Operations

In [78]:
m = torch.rand(2,3) # to not take new place in memort
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3379, 0.2170, 0.9454],
        [0.7116, 0.1157, 0.6574]])
tensor([[0.3451, 0.0453, 0.9798],
        [0.5548, 0.6868, 0.4920]])


In [79]:
m.add_(n)

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [80]:
m

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [81]:
n

tensor([[0.3451, 0.0453, 0.9798],
        [0.5548, 0.6868, 0.4920]])

In [82]:
torch.relu(m)

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [83]:
m.relu_()

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [84]:
m

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

## Copying a Tensor

In [85]:
a=torch.rand(2,3)
a

tensor([[0.0748, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [86]:
b=a  #probmle= if changes done in a will repflect in b too

In [87]:
b

tensor([[0.0748, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [88]:
a[0][0]=0

In [89]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [90]:
id(a)  #memory location

135321542021264

In [91]:
id(b)

135321542021264

In [92]:
b=a.clone()

In [93]:
a

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [94]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [95]:
a[0][1]=10

In [96]:
a

tensor([[ 0.0000, 10.0000,  0.3271],
        [ 0.0103,  0.9516,  0.2855]])

In [97]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [98]:
id(a)

135321542021264

In [99]:
id(b)

135321542028064

In [100]:
# tensor operation on gpu

In [101]:
torch.cuda.is_available()

True

In [102]:
device=torch.device('cuda')

In [103]:
#creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [105]:
#moving existing tensor on gpu
a=torch.rand(2,3)

In [106]:
a

tensor([[0.2324, 0.9141, 0.7668],
        [0.1659, 0.4393, 0.2243]])

In [107]:
b=a.to(device)

In [108]:
b+5

tensor([[5.2324, 5.9141, 5.7668],
        [5.1659, 5.4393, 5.2243]], device='cuda:0')

In [111]:
import time

size=10000

a_cpu=torch.randn(size,size)
b_cpu=torch.randn(size,size)

start_time=time.time()
result_cpu=torch.matmul(a_cpu,b_cpu) #matrix multiplication
cpu_time=time.time()-start_time


print(f'Time on cpu {cpu_time:.4f} seconds')


#moving to gpu
a_gpu=a_cpu.to(device)
b_gpu=b_cpu.to(device)

start_time=time.time()
result_gpu=torch.matmul(a_gpu,b_gpu)
torch.cuda.synchronize() #ensure all gpu operations are complete
gpu_time=time.time()-start_time


print(f'Time on cpu {cpu_time:.4f} seconds')

print("\n speedup (cpu time/gpu time)",cpu_time,gpu_time)










Time on cpu 14.4794 seconds
Time on cpu 14.4794 seconds

 speedup (cpu time/gpu time) 14.479433536529541 0.7882285118103027


In [113]:
# reshaping tensors
a=torch.ones(4,4)

In [114]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [117]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
b=torch.rand(2,3,4)
b

tensor([[[0.8499, 0.3817, 0.2436, 0.1008],
         [0.1176, 0.3651, 0.4549, 0.8776],
         [0.3721, 0.7827, 0.4926, 0.7323]],

        [[0.4682, 0.4369, 0.3151, 0.6987],
         [0.7903, 0.5187, 0.7766, 0.9718],
         [0.5460, 0.9329, 0.9847, 0.6817]]])

In [120]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [122]:
#unsqueez
#image size
c=torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [123]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape




torch.Size([20])

In [125]:
#numpy and pytorch

import numpy as np
a=torch.tensor([1,2,3])
a


tensor([1, 2, 3])

In [127]:
b=a.numpy()
b


array([1, 2, 3])

In [128]:
type(b)


numpy.ndarray

In [129]:
c=np.array([1,2,3])

In [130]:
torch.from_numpy(c)

tensor([1, 2, 3])